function getSecret(){
return "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5NDY3MDYxMCwiaWF0IjoxNjk0NjcwNjEwfQ.OTkCAHIpjJ0KLJhaaXat2-PjF4slE_uH_PTQZKShGkc"
};

module.exports = getSecret();
